{% set name = "pytest-html" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: b6a88cba507500d8709959201e2e757d3941e859fd17cfd4ed87b16fc0c67912

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  host:
    - pip
    - python
    - hatch-vcs >=0.3
    - hatchling >=1.13
  run:
    - python
    - jinja2 >=3
    - pytest >=7
    - pytest-metadata >=2

test:
  source_files:
    - testing
  requires:
    - pip
    - pytest
    - bs4
    - selenium
    - assertpy
  imports:
    - pytest_html
  commands:
    - pip check
    - pytest testing/test_unit.py -v

about:
  home: https://github.com/pytest-dev/pytest-html
  license: MPL-2.0
  license_family: Other
  license_file: LICENSE
  summary: pytest plugin for generating HTML reports
  description: |
    pytest plugin for generating HTML reports
  dev_url: https://github.com/pytest-dev/pytest-html
  doc_url: https://github.com/pytest-dev/pytest-html

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
    - nicoddemus
